name: Deployment
on:
  push:
    branches: [ main ]

jobs:
  Microservicio1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "763aff5c-1b42-43b4-83de-59b3d98a8f55"
          heroku_app_name: "microservicio-uno-grupo5"
          heroku_email: "jelimv@hotmail.com"
          appdir: "microservicio"

  Microservicio2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "763aff5c-1b42-43b4-83de-59b3d98a8f55"
          heroku_app_name: "microservicio-dos-grupo5"
          heroku_email: "jelimv@hotmail.com"
          appdir: "microservicio"

  Microservicio3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "763aff5c-1b42-43b4-83de-59b3d98a8f55"
          heroku_app_name: "microservicio-tres-grupo5"
          heroku_email: "jelimv@hotmail.com"
          appdir: "microservicio"

  Monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "763aff5c-1b42-43b4-83de-59b3d98a8f55"
          heroku_app_name: "monitor-grupo5"
          heroku_email: "jelimv@hotmail.com"
          appdir: "monitor"